-- AKAITSUKI stage 5
-- Run this in Supabase SQL Editor to switch titles from legacy JSON storage to normalized tables.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null default '',
  nickname text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.sync_profile_from_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, nickname, created_at, updated_at)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'nickname', ''),
    coalesce(new.created_at, now()),
    now()
  )
  on conflict (id) do update
  set
    email = excluded.email,
    nickname = case
      when excluded.nickname <> '' then excluded.nickname
      else public.profiles.nickname
    end,
    updated_at = now();

  return new;
end;
$$;

create table if not exists public.favorite_titles (
  user_id uuid not null references auth.users(id) on delete cascade,
  title_id bigint not null,
  created_at timestamptz not null default now(),
  primary key (user_id, title_id)
);

create table if not exists public.title_ratings (
  user_id uuid not null references auth.users(id) on delete cascade,
  title_id bigint not null,
  rating smallint not null check (rating between 1 and 10),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, title_id)
);

create table if not exists public.site_content (
  key text primary key,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.titles (
  id bigint generated by default as identity primary key,
  title text not null default '',
  type text not null default 'anime',
  year integer not null default extract(year from now()),
  season text not null default '',
  status text not null default '',
  rating numeric(3, 1) not null default 0,
  duration text not null default '',
  team text not null default '',
  voiceover text not null default '',
  description text not null default '',
  long_text text not null default '',
  poster_theme text not null default 'electric-violet',
  poster_url text not null default '',
  poster_gradient text not null default '',
  video_url text not null default '',
  channel text not null default '',
  release_date text not null default '',
  linked_title_id bigint null,
  latest_episode text not null default '',
  updated_order integer not null default 2147483647,
  popularity numeric(6, 2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.title_alt_titles (
  title_id bigint not null references public.titles(id) on delete cascade,
  position integer not null,
  value text not null default '',
  primary key (title_id, position)
);

create table if not exists public.title_genres (
  title_id bigint not null references public.titles(id) on delete cascade,
  position integer not null,
  value text not null default '',
  primary key (title_id, position)
);

create table if not exists public.title_categories (
  title_id bigint not null references public.titles(id) on delete cascade,
  position integer not null,
  value text not null default '',
  primary key (title_id, position)
);

create table if not exists public.title_seasons (
  id text primary key,
  title_id bigint not null references public.titles(id) on delete cascade,
  number integer not null default 1,
  position integer not null default 1
);

create table if not exists public.title_episodes (
  id text primary key,
  title_id bigint not null references public.titles(id) on delete cascade,
  season_id text not null references public.title_seasons(id) on delete cascade,
  number integer not null default 1,
  title text not null default '',
  is_deleted boolean not null default false,
  position integer not null default 1
);

create table if not exists public.episode_voiceovers (
  id text primary key,
  title_id bigint not null references public.titles(id) on delete cascade,
  episode_id text not null references public.title_episodes(id) on delete cascade,
  name text not null default '',
  position integer not null default 1
);

create table if not exists public.voiceover_players (
  id text primary key,
  title_id bigint not null references public.titles(id) on delete cascade,
  voiceover_id text not null references public.episode_voiceovers(id) on delete cascade,
  name text not null default '',
  src text not null default '',
  position integer not null default 1
);

create index if not exists profiles_email_idx on public.profiles (email);
create index if not exists favorite_titles_title_id_idx on public.favorite_titles (title_id);
create index if not exists title_ratings_title_id_idx on public.title_ratings (title_id);
create index if not exists titles_type_idx on public.titles (type);
create index if not exists titles_updated_order_idx on public.titles (updated_order);
create index if not exists title_alt_titles_title_id_idx on public.title_alt_titles (title_id, position);
create index if not exists title_genres_title_id_idx on public.title_genres (title_id, position);
create index if not exists title_categories_title_id_idx on public.title_categories (title_id, position);
create index if not exists title_seasons_title_id_idx on public.title_seasons (title_id, position);
create index if not exists title_episodes_title_id_idx on public.title_episodes (title_id, season_id, position);
create index if not exists episode_voiceovers_title_id_idx on public.episode_voiceovers (title_id, episode_id, position);
create index if not exists voiceover_players_title_id_idx on public.voiceover_players (title_id, voiceover_id, position);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.current_app_role()
returns text
language sql
stable
as $$
  select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', 'user');
$$;

create or replace function public.import_legacy_titles_payload(payload jsonb)
returns void
language plpgsql
as $$
declare
  title_item jsonb;
  season_item jsonb;
  episode_item jsonb;
  voiceover_item jsonb;
  player_item jsonb;
  title_id bigint;
  season_id text;
  episode_id text;
  voiceover_id text;
  title_index integer;
  season_index integer;
  episode_index integer;
  voiceover_index integer;
  player_index integer;
begin
  if jsonb_typeof(payload) is distinct from 'array' then
    return;
  end if;

  delete from public.titles;

  title_index := 0;
  for title_item in select value from jsonb_array_elements(payload) loop
    title_index := title_index + 1;
    title_id := coalesce(nullif(title_item ->> 'id', '')::bigint, title_index::bigint);

    insert into public.titles (
      id,
      title,
      type,
      year,
      season,
      status,
      rating,
      duration,
      team,
      voiceover,
      description,
      long_text,
      poster_theme,
      poster_url,
      poster_gradient,
      video_url,
      channel,
      release_date,
      linked_title_id,
      latest_episode,
      updated_order,
      popularity
    )
    values (
      title_id,
      coalesce(title_item ->> 'title', ''),
      coalesce(title_item ->> 'type', 'anime'),
      coalesce(nullif(title_item ->> 'year', '')::integer, extract(year from now())::integer),
      coalesce(title_item ->> 'season', ''),
      coalesce(title_item ->> 'status', ''),
      coalesce(nullif(title_item ->> 'rating', '')::numeric, 0),
      coalesce(title_item ->> 'duration', ''),
      coalesce(title_item ->> 'team', ''),
      coalesce(title_item ->> 'voiceover', title_item ->> 'team', ''),
      coalesce(title_item ->> 'description', ''),
      coalesce(title_item ->> 'longText', ''),
      coalesce(title_item ->> 'posterTheme', 'electric-violet'),
      coalesce(title_item ->> 'posterUrl', ''),
      coalesce(title_item ->> 'posterGradient', title_item ->> 'poster', ''),
      coalesce(title_item ->> 'videoUrl', ''),
      coalesce(title_item ->> 'channel', ''),
      coalesce(title_item ->> 'releaseDate', ''),
      nullif(title_item ->> 'linkedTitleId', '')::bigint,
      coalesce(title_item ->> 'latestEpisode', ''),
      coalesce(nullif(title_item ->> 'updatedOrder', '')::integer, 2147483647),
      coalesce(nullif(title_item ->> 'popularity', '')::numeric, nullif(title_item ->> 'rating', '')::numeric, 0)
    )
    on conflict (id) do update
    set
      title = excluded.title,
      type = excluded.type,
      year = excluded.year,
      season = excluded.season,
      status = excluded.status,
      rating = excluded.rating,
      duration = excluded.duration,
      team = excluded.team,
      voiceover = excluded.voiceover,
      description = excluded.description,
      long_text = excluded.long_text,
      poster_theme = excluded.poster_theme,
      poster_url = excluded.poster_url,
      poster_gradient = excluded.poster_gradient,
      video_url = excluded.video_url,
      channel = excluded.channel,
      release_date = excluded.release_date,
      linked_title_id = excluded.linked_title_id,
      latest_episode = excluded.latest_episode,
      updated_order = excluded.updated_order,
      popularity = excluded.popularity,
      updated_at = now();

    insert into public.title_alt_titles (title_id, position, value)
    select title_id, ord::integer, trim(value)
    from jsonb_array_elements_text(coalesce(title_item -> 'altTitles', '[]'::jsonb)) with ordinality as t(value, ord)
    where trim(value) <> '';

    insert into public.title_genres (title_id, position, value)
    select title_id, ord::integer, trim(value)
    from jsonb_array_elements_text(coalesce(title_item -> 'genres', '[]'::jsonb)) with ordinality as t(value, ord)
    where trim(value) <> '';

    insert into public.title_categories (title_id, position, value)
    select title_id, ord::integer, trim(value)
    from jsonb_array_elements_text(coalesce(title_item -> 'categories', '[]'::jsonb)) with ordinality as t(value, ord)
    where trim(value) <> '';

    if jsonb_typeof(title_item #> '{media,seasons}') = 'array' then
      season_index := 0;
      for season_item in select value from jsonb_array_elements(title_item #> '{media,seasons}') loop
        season_index := season_index + 1;
        season_id := coalesce(nullif(season_item ->> 'id', ''), gen_random_uuid()::text);

        insert into public.title_seasons (id, title_id, number, position)
        values (
          season_id,
          title_id,
          coalesce(nullif(season_item ->> 'number', '')::integer, season_index),
          season_index
        );

        if jsonb_typeof(season_item -> 'episodes') = 'array' then
          episode_index := 0;
          for episode_item in select value from jsonb_array_elements(season_item -> 'episodes') loop
            episode_index := episode_index + 1;
            episode_id := coalesce(nullif(episode_item ->> 'id', ''), gen_random_uuid()::text);

            insert into public.title_episodes (id, title_id, season_id, number, title, is_deleted, position)
            values (
              episode_id,
              title_id,
              season_id,
              coalesce(nullif(episode_item ->> 'number', '')::integer, episode_index),
              coalesce(episode_item ->> 'title', ''),
              coalesce((episode_item ->> 'isDeleted')::boolean, false),
              episode_index
            );

            if jsonb_typeof(episode_item -> 'voiceovers') = 'array' then
              voiceover_index := 0;
              for voiceover_item in select value from jsonb_array_elements(episode_item -> 'voiceovers') loop
                voiceover_index := voiceover_index + 1;
                voiceover_id := coalesce(nullif(voiceover_item ->> 'id', ''), gen_random_uuid()::text);

                insert into public.episode_voiceovers (id, title_id, episode_id, name, position)
                values (
                  voiceover_id,
                  title_id,
                  episode_id,
                  coalesce(nullif(trim(voiceover_item ->> 'name'), ''), format('Озвучка %s', voiceover_index)),
                  voiceover_index
                );

                if jsonb_typeof(voiceover_item -> 'players') = 'array' then
                  player_index := 0;
                  for player_item in select value from jsonb_array_elements(voiceover_item -> 'players') loop
                    player_index := player_index + 1;

                    insert into public.voiceover_players (id, title_id, voiceover_id, name, src, position)
                    values (
                      coalesce(nullif(player_item ->> 'id', ''), gen_random_uuid()::text),
                      title_id,
                      voiceover_id,
                      coalesce(nullif(trim(player_item ->> 'name'), ''), format('Плеер %s', player_index)),
                      coalesce(player_item ->> 'src', player_item ->> 'iframe', ''),
                      player_index
                    );
                  end loop;
                end if;
              end loop;
            end if;
          end loop;
        end if;
      end loop;
    end if;
  end loop;
end;
$$;

alter table public.profiles enable row level security;
alter table public.favorite_titles enable row level security;
alter table public.title_ratings enable row level security;
alter table public.site_content enable row level security;
alter table public.titles enable row level security;
alter table public.title_alt_titles enable row level security;
alter table public.title_genres enable row level security;
alter table public.title_categories enable row level security;
alter table public.title_seasons enable row level security;
alter table public.title_episodes enable row level security;
alter table public.episode_voiceovers enable row level security;
alter table public.voiceover_players enable row level security;

drop policy if exists profiles_select_self on public.profiles;
create policy profiles_select_self
  on public.profiles
  for select
  to authenticated
  using (auth.uid() = id);

drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self
  on public.profiles
  for insert
  to authenticated
  with check (auth.uid() = id);

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self
  on public.profiles
  for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists favorites_select_self on public.favorite_titles;
create policy favorites_select_self
  on public.favorite_titles
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists favorites_insert_self on public.favorite_titles;
create policy favorites_insert_self
  on public.favorite_titles
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists favorites_delete_self on public.favorite_titles;
create policy favorites_delete_self
  on public.favorite_titles
  for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists ratings_select_all on public.title_ratings;
create policy ratings_select_all
  on public.title_ratings
  for select
  to anon, authenticated
  using (true);

drop policy if exists ratings_insert_self on public.title_ratings;
create policy ratings_insert_self
  on public.title_ratings
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists ratings_update_self on public.title_ratings;
create policy ratings_update_self
  on public.title_ratings
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists site_content_select_public on public.site_content;
create policy site_content_select_public
  on public.site_content
  for select
  to anon, authenticated
  using (true);

drop policy if exists site_content_insert_admin on public.site_content;
create policy site_content_insert_admin
  on public.site_content
  for insert
  to authenticated
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists site_content_update_admin on public.site_content;
create policy site_content_update_admin
  on public.site_content
  for update
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'))
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists site_content_delete_admin on public.site_content;
create policy site_content_delete_admin
  on public.site_content
  for delete
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'));

drop policy if exists titles_select_public on public.titles;
create policy titles_select_public
  on public.titles
  for select
  to anon, authenticated
  using (true);

drop policy if exists titles_insert_admin on public.titles;
create policy titles_insert_admin
  on public.titles
  for insert
  to authenticated
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists titles_update_admin on public.titles;
create policy titles_update_admin
  on public.titles
  for update
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'))
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists titles_delete_admin on public.titles;
create policy titles_delete_admin
  on public.titles
  for delete
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'));

drop policy if exists title_alt_titles_select_public on public.title_alt_titles;
create policy title_alt_titles_select_public
  on public.title_alt_titles
  for select
  to anon, authenticated
  using (true);

drop policy if exists title_alt_titles_insert_admin on public.title_alt_titles;
create policy title_alt_titles_insert_admin
  on public.title_alt_titles
  for insert
  to authenticated
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists title_alt_titles_update_admin on public.title_alt_titles;
create policy title_alt_titles_update_admin
  on public.title_alt_titles
  for update
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'))
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists title_alt_titles_delete_admin on public.title_alt_titles;
create policy title_alt_titles_delete_admin
  on public.title_alt_titles
  for delete
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'));

drop policy if exists title_genres_select_public on public.title_genres;
create policy title_genres_select_public
  on public.title_genres
  for select
  to anon, authenticated
  using (true);

drop policy if exists title_genres_insert_admin on public.title_genres;
create policy title_genres_insert_admin
  on public.title_genres
  for insert
  to authenticated
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists title_genres_update_admin on public.title_genres;
create policy title_genres_update_admin
  on public.title_genres
  for update
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'))
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists title_genres_delete_admin on public.title_genres;
create policy title_genres_delete_admin
  on public.title_genres
  for delete
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'));

drop policy if exists title_categories_select_public on public.title_categories;
create policy title_categories_select_public
  on public.title_categories
  for select
  to anon, authenticated
  using (true);

drop policy if exists title_categories_insert_admin on public.title_categories;
create policy title_categories_insert_admin
  on public.title_categories
  for insert
  to authenticated
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists title_categories_update_admin on public.title_categories;
create policy title_categories_update_admin
  on public.title_categories
  for update
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'))
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists title_categories_delete_admin on public.title_categories;
create policy title_categories_delete_admin
  on public.title_categories
  for delete
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'));

drop policy if exists title_seasons_select_public on public.title_seasons;
create policy title_seasons_select_public
  on public.title_seasons
  for select
  to anon, authenticated
  using (true);

drop policy if exists title_seasons_insert_admin on public.title_seasons;
create policy title_seasons_insert_admin
  on public.title_seasons
  for insert
  to authenticated
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists title_seasons_update_admin on public.title_seasons;
create policy title_seasons_update_admin
  on public.title_seasons
  for update
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'))
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists title_seasons_delete_admin on public.title_seasons;
create policy title_seasons_delete_admin
  on public.title_seasons
  for delete
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'));

drop policy if exists title_episodes_select_public on public.title_episodes;
create policy title_episodes_select_public
  on public.title_episodes
  for select
  to anon, authenticated
  using (true);

drop policy if exists title_episodes_insert_admin on public.title_episodes;
create policy title_episodes_insert_admin
  on public.title_episodes
  for insert
  to authenticated
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists title_episodes_update_admin on public.title_episodes;
create policy title_episodes_update_admin
  on public.title_episodes
  for update
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'))
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists title_episodes_delete_admin on public.title_episodes;
create policy title_episodes_delete_admin
  on public.title_episodes
  for delete
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'));

drop policy if exists episode_voiceovers_select_public on public.episode_voiceovers;
create policy episode_voiceovers_select_public
  on public.episode_voiceovers
  for select
  to anon, authenticated
  using (true);

drop policy if exists episode_voiceovers_insert_admin on public.episode_voiceovers;
create policy episode_voiceovers_insert_admin
  on public.episode_voiceovers
  for insert
  to authenticated
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists episode_voiceovers_update_admin on public.episode_voiceovers;
create policy episode_voiceovers_update_admin
  on public.episode_voiceovers
  for update
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'))
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists episode_voiceovers_delete_admin on public.episode_voiceovers;
create policy episode_voiceovers_delete_admin
  on public.episode_voiceovers
  for delete
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'));

drop policy if exists voiceover_players_select_public on public.voiceover_players;
create policy voiceover_players_select_public
  on public.voiceover_players
  for select
  to anon, authenticated
  using (true);

drop policy if exists voiceover_players_insert_admin on public.voiceover_players;
create policy voiceover_players_insert_admin
  on public.voiceover_players
  for insert
  to authenticated
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists voiceover_players_update_admin on public.voiceover_players;
create policy voiceover_players_update_admin
  on public.voiceover_players
  for update
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'))
  with check (public.current_app_role() in ('owner', 'admin'));

drop policy if exists voiceover_players_delete_admin on public.voiceover_players;
create policy voiceover_players_delete_admin
  on public.voiceover_players
  for delete
  to authenticated
  using (public.current_app_role() in ('owner', 'admin'));

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function public.sync_profile_from_auth_user();

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists title_ratings_touch_updated_at on public.title_ratings;
create trigger title_ratings_touch_updated_at
before update on public.title_ratings
for each row execute function public.touch_updated_at();

drop trigger if exists site_content_touch_updated_at on public.site_content;
create trigger site_content_touch_updated_at
before update on public.site_content
for each row execute function public.touch_updated_at();

drop trigger if exists titles_touch_updated_at on public.titles;
create trigger titles_touch_updated_at
before update on public.titles
for each row execute function public.touch_updated_at();

insert into public.site_content (key, payload)
values
  ('titles', '[]'::jsonb),
  ('about', '{}'::jsonb)
on conflict (key) do nothing;

do $$
declare
  legacy_titles jsonb;
begin
  if exists (select 1 from public.site_content where key = 'titles')
    and not exists (select 1 from public.titles limit 1) then
    select payload into legacy_titles
    from public.site_content
    where key = 'titles';

    if jsonb_typeof(legacy_titles) = 'array' and jsonb_array_length(legacy_titles) > 0 then
      perform public.import_legacy_titles_payload(legacy_titles);
    end if;
  end if;
end;
$$;
